language: node_js

node_js:
  - "8"

before_script:
- export TZ=America/New_York
- npm run build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: deploy-storybook-travis
  local_dir: storybook-static
